### ISSUE TITLE
`pkg-config` should be an automatic flag

### ISSUE THREAD

**Issue by hasufell** [TeofilC/digest#20]
If it's an automatic flag and enabled by default, cabal can automatically fall back to non-pkg-config way of finding/using the C library zlib. Otherwise (e.g. if pkg-config is not installed) the build will just outright fail, which does not make sense.

**Comment by TeofilC** [comment]
Thanks @hasufell! This seems reasonable. I've implemented this in #21. And released this as https://hackage.haskell.org/package/digest-0.0.2.1
